version: '2.1'

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    depends_on:
      - "database"
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    depends_on:
      - "database"
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    depends_on:
      - "database"
    networks:
      - servers
    ports:
      - "8082:8080"

  database:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "8070:8070"
