FROM golang:1.15 as build

RUN apt-get update && apt-get install -y ninja-build

# TODO: Змініть на власну реалізацію системи збірки
RUN go get -u github.com/stormtrooper01/cse2_lab2/build/cmd/bood

WORKDIR /go/src/practice-2
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
# ENTRYPOINT ["bood", "integration-tests"]
RUN mv build.bood build/product/ && mv build/test/build.bood . && CGO_ENABLED=0
ENTRYPOINT ["bood"]
